on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements.txt
      - name: Run tests
        run: coverage run -m unittest discover
      - name: Report code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: d075a7a68749e26b1932888304319b62fcd65d6318895c4cebdf75e3765447fa
        with:
          coverageCommand: coverage xml

  build:
    needs: [ test ]
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t roobre/reposettings
